# -*- coding: utf-8 -*-
"""baraj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZOYGDVrLTC7fErLUst8aPp3PbjAWm6N
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


barajlar = ["Balçova Barajı","Gördes Barajı","Tahtalı Barajı","Ürkmez Barajı","Güzelhisar Barajı","Alaçatı Kutlu Aktaş Barajı"]
doluluk_oranlari = [12.96, 1.57,	12.05,	6.55,	64.98,	7.54]


data = pd.DataFrame({
    "Baraj": barajlar,
    "Doluluk Oranı (%)": doluluk_oranlari
})

plt.figure(figsize=(10, 6))
sns.set_theme(style="whitegrid")


sns.barplot(x="Doluluk Oranı (%)", y="Baraj", data=data, palette="coolwarm")

plt.title("İzmir Barajları Doluluk Oranları", fontsize=16)
plt.xlabel("Doluluk Oranı (%)", fontsize=12)
plt.ylabel("Barajlar", fontsize=12)

plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 8))
plt.pie(doluluk_oranlari, labels=barajlar, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("pastel"))

plt.title("İzmir Barajları Doluluk Oranları (Pasta Grafiği)", fontsize=16)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(barajlar, doluluk_oranlari, marker='o', linestyle='-', color='b', label="Doluluk Oranı")

plt.title("İzmir Barajları Doluluk Oranları", fontsize=16)
plt.xlabel("Barajlar", fontsize=12)
plt.ylabel("Doluluk Oranı (%)", fontsize=12)
plt.xticks(rotation=45)
plt.legend()

plt.tight_layout()
plt.show()